### ISSUE TITLE
threads build on mac

### ISSUE THREAD

**Issue by ddkn** [afify/sfm#13]
Hi @afify,

So I figured the pull request was not a good place for this conversation. I went to build on mac with and I am seeing this,

~~~
$ make
sfm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wextra -Wvla -O3 -g -DVERSION="0.1" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -D_BSD_SOURCE
LDFLAGS  = -pthread -s
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wextra -Wvla -O3 -g -DVERSION=\"0.1\" -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -D_BSD_SOURCE sfm.c
sfm.c:481:6: error: use of undeclared identifier 'show_perm'
        if (show_perm == 1) {
            ^
sfm.c:488:6: error: use of undeclared identifier 'show_ug'
        if (show_ug == 1) {
            ^
sfm.c:499:6: error: use of undeclared identifier 'show_dt'
        if (show_dt == 1) {
            ^
sfm.c:508:6: error: use of undeclared identifier 'show_size'
        if (show_size == 1 && S_ISREG(cursor->mode)) {
            ^
sfm.c:588:44: warning: format specifies type 'long' but the argument has type 'off_t' (aka 'long long') [-Wformat]
        if (snprintf(result, result_len, "%ld%c", size, unit) < 0)
                                          ~~~     ^~~~
                                          %lld
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^~~~~~~~~~~
sfm.c:1144:12: warning: variable length array used [-Wvla]
        char *argv[argc + 2];
                  ^
2 warnings and 4 errors generated.
make: *** [sfm.o] Error 1
~~~

Which is the same error I am getting on OpenBSD. It seems you have the structs defined in *sfm.c* but the variables defined in *config.def.h*. I am sure this is something you are seeing.

**Comment by afify** [comment]
Merge main to threads will fix the issue I think

**Comment by ddkn** [comment]
That fixed the compiling issue, but upon quitting, `q`, the program just locks up. Also, perhaps this is the issue you mentioned but the screen isn't updating on mac or OpenBSD.

**Comment by afify** [comment]
> That fixed the compiling issue, but upon quitting, `q`, the program just locks up. Also, perhaps this is the issue you mentioned but the screen isn't updating on mac or OpenBSD.

That's right I'm facing this issue on OSX and *BSD, works fine on GNU

**Comment by afify** [comment]
@ddkn  Please test new update in theads branch

**Comment by ddkn** [comment]
Hi @afify,

So I tested the new *threads* branch at 55c4b0e from a clean repo (just in case) on both macOS 10.13 and OpenBSD 6.9. The features of copy/move/delete work, *however*, the screen is still not updating until you change directories. Also, quit `q` still locks up the terminal and it needs to be killed; this means `^C` doesn't end the program as one would expect. This is happening on both systems.

I also checked in and out of tmux in case, but it gave the same result.

I also found I had a Debian Buster install floating around, just to make sure I wasn't doing anything dumb. Your package works as you intended on Debian, as you mentioned in the Pull Request.

**Comment by afify** [comment]
@ddkn a6320a16a678bbd5a891aab951637ff0b139770e should fix OSX and BSD issues

**Comment by ddkn** [comment]
Hi @afify,

I tried out the 6607b36 commit and quit `q` now works, but copying/moving/deleting still does not update on the screen. I still need to move back then forward for it to update. (In and out of tmux on macOS). This was also the case for 80cb4ae (the newer commit).

Actually on macOS 10.13, creating a directory shows up on the screen. However, on OpenBSD 6.9 creating a directory does not show up until one moves backwards or forwards.

**Comment by afify** [comment]
Hi @ddkn please check a598a2e8c966808f72c2fa9d2c17281eb60ce894

**Comment by ddkn** [comment]
Hi @afify, unfortunately I don't have good news. I tried on both systems (macOS + OpenBSD), and no change for me. It still only refreshes the screen when I move directories. 

Sorry for being late, I have been busy with work.

**Comment by afify** [comment]
@ddkn please check 0c9bedd25468b2278deebfb5a02992e8e276e5c7
i've tested on OpenBSD FreeBSD vm it works fine

**Comment by ddkn** [comment]
Hi @afify ,

So I checked both 0c9bedd and 5d1c834, so it works (sort of). I am able to copy files and see them update, however, it only copies a subset of files on both systems. If I copy 5 it may paste 3; this happens on both systems (see below for a video of both). Also, in some cases I can get it to trigger a segfault on *delete* `d`, when I select too many files, there is a "Cannot allocate memory" on mac and a core dump on OpenBSD.

Video demonstrations
* [macOS](https://asciinema.org/a/DO6yUbC955zUY1XOpWOQFF4LI)
* [OpenBSD](https://asciinema.org/a/bHSu8GBv9osV0TQgZYTCI1f9v)
* [Segfault](https://asciinema.org/a/CXPOgdJr3lpfC8mP4WeJwabbJ)

**Comment by afify** [comment]
> Hi @afify ,
> 
> So I checked both 0c9bedd and 5d1c834, so it works (sort of). I am able to copy files and see them update, however, it only copies a subset of files on both systems. If I copy 5 it may paste 3; this happens on both systems (see below for a video of both). Also, in some cases I can get it to trigger a segfault on *delete* `d`, when I select too many files, there is a "Cannot allocate memory" on mac and a core dump on OpenBSD.
> 
> Video demonstrations
> * [macOS](https://asciinema.org/a/DO6yUbC955zUY1XOpWOQFF4LI)
> * [OpenBSD](https://asciinema.org/a/bHSu8GBv9osV0TQgZYTCI1f9v)
> * [Segfault](https://asciinema.org/a/CXPOgdJr3lpfC8mP4WeJwabbJ)
> 
> In my case I run on dedicated hardware for OpenBSD, which I have two machines a laptop and a server. Both exhibit the same issue. And for additional context on OpenBSD I run `xterm` and an mac I am running their vanilla `Terminal v2.8.3`.

@ddkn thanks for your helpful videos. these are new issues I think, at least threads build is done. We can create new issue "visual copy"

**Comment by ddkn** [comment]
Awesome, glad it was helpful, I will create a new issue.
