### ISSUE TITLE
Visual copy

### ISSUE THREAD

**Issue by ddkn** [afify/sfm#16]
Hi @afify ,

As requested, here is the new issue explaining the *visual copy* problem.

I am able to copy files and see them update, however, it only copies a subset of files on both systems. If I copy 5 it may paste 3; this happens on both systems (see below for a video of both). Also, in some cases I can get it to trigger a segfault on *delete* `d`, when I select too many files, there is a "Cannot allocate memory" on mac and a core dump on OpenBSD.

Video demonstrations
* [macOS](https://asciinema.org/a/415005)
* [OpenBSD](https://asciinema.org/a/415007)
* [Segfault](https://asciinema.org/a/415011)

In my case I run on dedicated hardware for OpenBSD, which I have two machines a laptop and a server. Both exhibit the same issue. And for additional context on OpenBSD I run `xterm` and an mac I am running their vanilla `Terminal v2.8.3`.

**Comment by ddkn** [comment]
Hi Afify,

Just a small update, I tried on my systems here. I noticed that the first copy acts weird (like before), but subsequent copies seem to work with updates to the screen? Unless the amount of files is too big, then it has a hard time sometimes.

Hope all is well!

**Comment by afify** [comment]
Hi @ddkn 

I'm just stuck in a loop 😄, new commits:
    - thread send signal to parent (keep thread safe and away from race condition)
    - parent handle signal and run `listdir()` (here i'm 7b0060575657e47ca9edadfd4ebc01e73f8fb72e)
the issue now is with `listdir()`:
    - if you copy 3 files it will run `listdir()` 3 times the problem happens when running `listdir()` many times

**Comment by ddkn** [comment]
No worries! I was just letting you know I didn't disappear. I am back on some of my projects at the moment for school. So I can provide testing when you need it.

**Comment by afify** [comment]
@ddkn please test ab67e2e56f7eb99b7172b4cca689cb67d87405e4

**Comment by ddkn** [comment]
So I tried out ab67e2e, I found on the mac it wouldn't update the screen initial copy, (going back and forward refreshed correctly), but subsequent copies work just fine, and the screen updates as expected.

OpenBSD, however, is having a different problem. I am able to copy the first time, but subsequent copies 'claim' to work but no files are copied, and upon hitting `q` to quit, `sfm` just locks up.

**Comment by afify** [comment]
@ddkn please test c12db64edd1721d56dafb4353be4abf6d8d42c6a 🙏

**Comment by afify** [comment]
Hi @ddkn 
OpenBSD works fine now a0c177107f8434675afaea0aef2e9ccf79d9d0e7 please test

**Comment by ddkn** [comment]
Hi @afify,

I have the opposite results. On my macOS 10.13 high Sierra (tmux and no tmux), everything cp/mv/rm works as expected! 

~~However, OpenBSD I still need to move back and forward in a directroy for changes to take effect, and subsequent copies are not displaying.~~

I noticed, if I move back a directory and copy/move it works just fine. However, if I **create** a directory `N test` and try to move contents into there it doesn't update the screen. This problem doesn't exist on the mac so far.

**Comment by afify** [comment]
Hi @ddkn,
Facing any issue for this topic ?

**Comment by ddkn** [comment]
Hi @afify 

Sorry for taking so long to get back, I was a bit preoccupied. I just tested on OpenBSD 6.9 and macOS 10.13.6 with d8bcfd3, and the copy, move, yank, and delete seem to work when copying between directories!

So far things seem to be working good on my side!
