### ISSUE TITLE
Scrolling doesn't work properly

### ISSUE THREAD

**Issue by sikmir** [afify/sfm#18]
### Steps to reproduce
1. There is a folder with a lot of files (e.g. 300)
2. Start sfm
3. Scroll from top to bottom (using `Pg-Dn` or `j`)
4. Scroll back to top (using `Pg-Up` or `k`)

### Actual behaviour
There is no way to scroll to actual top. 

### Expected behaviour
It should be possible to scroll up to actual top.

### Configuration
https://github.com/afify/sfm/commit/581a36848dd6a398f6ac5f2461400cbf64da8a1b

**Comment by afify** [comment]
@sikmir please test 700ef1307424cd1e364da406b012c189ec68dfca

**Comment by sikmir** [comment]
That's fine now. Thanks for your great suckless tool!
