### ISSUE TITLE
Breakage

### ISSUE THREAD

**Issue by ashincoder** [afify/sfm#22]
Does'nt open after installation. error show `[FAILED 1773] tb_init()`

**Comment by afify** [comment]
sfm -v
uname -srvp

**Comment by ashincoder** [comment]
❯ sfm -v
sfm-0.2

❯ uname -srvp
Linux 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 unknown

**Comment by afify** [comment]
echo $TERM if empty
try : export TERM=xterm

**Comment by ashincoder** [comment]
❯ echo $TERM
st-256color

**Comment by afify** [comment]
please try build e27ad59517b2be47404afa8dd58c9e5bf5e72848

**Comment by ashincoder** [comment]
Ok I will try

**Comment by ashincoder** [comment]
Now it is showing TB_EUNSUPPORTED_TERMINAL

**Comment by afify** [comment]
`echo $TERMINFO`
`echo $TERMINFO_DIRS`
`cat $HOME/.terminfo`

**Comment by ashincoder** [comment]
❯ echo $TERMINFO
/home/ashin/.local/share/

❯ echo $TERMINFO
/home/ashin/.local/share/terminfo

**Comment by afify** [comment]
ls $TERMINFO/s/

**Comment by ashincoder** [comment]
There is no such file or directory

**Comment by ashincoder** [comment]
But i have a terminfo folder in the /usr/share/terminfo

**Comment by afify** [comment]
try to unset $TERMINFO
```sh
export -n TERMINFO
```

**Comment by ashincoder** [comment]
ok

**Comment by ashincoder** [comment]
Still errro

**Comment by afify** [comment]
> There is no such file or directory

termbox search in 2 location before trying /usr/share/terminfo/ :
$TERMINFO & $TERMINFO_DIRS 
if these env vars have wrong data it will not reach the `/usr/share/terminfo`
try to unset both ( $TERMINFO & $TERMINFO_DIRS) or add valid path in them

```sh
unset TERM TERMINFO
```

**Comment by ashincoder** [comment]
I did that
Still show

**Comment by ashincoder** [comment]
I will show a recording confuses the hello out of me

**Comment by afify** [comment]
```sh
ls -l /usr/share/terminfo/s/st-256color
```

**Comment by ashincoder** [comment]
❯ ls -l /usr/share/terminfo/s/st-256color
.rw-r--r-- 2.6k root 18 Jul 08:50  /usr/share/terminfo/s/st-256color

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/126069166-527f32dc-61d0-4261-8cea-dffd4c08a9ed.mp4

**Comment by afify** [comment]
That's normal because you unset them in this session only.
for global config, find out where these env vars are set ( .profile, .xinitrc,  .bashrc or your shell config)

**Comment by ashincoder** [comment]
They were set in the .zshenv file. They were removed still showing

**Comment by ashincoder** [comment]
I think I have to restart my machine.

**Comment by afify** [comment]
@ashincoder if solved please close the issue

**Comment by ashincoder** [comment]
Ok
