### ISSUE TITLE
No correct selection line re-drawing in fullscreen

### ISSUE THREAD

**Issue by anverb** [afify/sfm#24]
Hello! Here I have a visual issue: in fullscreen when you go to directory, selection line from previous directory and some very long file names are displaying. It's hard to explain, so, screens. 

Here I'll go to "somedirectories" 
![1](https://user-images.githubusercontent.com/88091752/127323911-4947b354-6f4e-4c23-a37c-17ff499a0b55.png)
And here what I have 
![2](https://user-images.githubusercontent.com/88091752/127323934-db4f5a5c-90da-481c-9959-a2b300fa0ab9.png)

**Comment by anverb** [comment]
Also, I've noticed that it cames only if sfm spawned with other windows and then used in fullscreen, like single window.

**Comment by afify** [comment]
please test b30cd816dee6ad3d05e540e5dad33da7fcb03e64

**Comment by anverb** [comment]
@afify Thank you, works perfectly!
