### ISSUE TITLE
Issue with opening sfm from a script/dmenu

### ISSUE THREAD

**Issue by zyx42** [afify/sfm#32]
An issue that I spotted is when I try to run sfm from a script, it fails to start.
I tried "st -e sfm", "st sfm" or just a script with sfm, but nothing succeded unfortunately.

**Comment by viyoriya** [comment]
https://github.com/afify/sfm/issues/26

**Comment by zyx42** [comment]
yes, thanks @viyoriya , it totally helped.

Sorry for the duplicate issue, but it might be worth either replacing those termbox.c, termbox.h and utf8.c files or just mention this issue somewhere on readme for now.
