### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by zyx42** [afify/sfm#33]
Would be really nice to see an option of setting custom colors, for example, in the config.h file.

**Comment by afify** [comment]
what do you mean by "custom colors" ?

**Comment by zyx42** [comment]
I mean something similar to what we have on dwm, on config.h there is "appearance" section with colors for elements of dwm(like foreground, background and border).

I did see on config.def.h section with "colors", but values there are a bit counter-intuitive(not hexadecimal) and changing them didn't do anything, so maybe I missed something?
Is there a way to customize colors? If not, then it would be nice to have one. If yes, then it would be nice to know how that can be achieved.

**Comment by afify** [comment]
> changing them didn't do anything

try to make changes in config.h

> not hexadecimal

yes this is a good feature, any pull request will be very helpfull
