### ISSUE TITLE
2 panes

### ISSUE THREAD

**Issue by engjpacheco** [afify/sfm#45]
I found sfm wonderfull, but in my opinion (sense of taste, if you will), I feel rare having 2 panes, is there an option or a flag to only have 1 pane, or do I need to modify sfm.c in order to achieve that.

Thansk in advance!!!

**Comment by afify** [comment]
diff --git a/sfm.c b/sfm.c
index 3a69586..9025796 100644
--- a/sfm.c
+++ b/sfm.c
@@ -2008,7 +2008,7 @@ start(void)
 	PERROR(start_signal() < 0);
 	PERROR(fsev_init() < 0);
 	PERROR(listdir(&panes[Left]) < 0);
-	PERROR(listdir(&panes[Right]) < 0);
+	//PERROR(listdir(&panes[Right]) < 0);
 	tb_present();
 
 	pthread_create(&fsev_thread, NULL, read_th, NULL);

**Comment by engjpacheco** [comment]
Thnks that works just fine but, there is the blank space any sugestión on how to delete that right panel blank space?
