### ISSUE TITLE
[Feature request] - Add file type specific icons

### ISSUE THREAD

**Issue by gabrielzschmitz** [afify/sfm#47]
Maybe using the same system used to default apps, and using blank as fallback. Probably better to have it in a separate file than making config.h too large.

**Comment by afify** [comment]
HI @gabrielzschmitz, pull requests are welcomed.

**Comment by gabrielzschmitz** [comment]
Added to sfm-patches repo [#12](https://github.com/afify/sfm-patches/pull/12)
