### ISSUE TITLE
have other pane to preview directory/files

### ISSUE THREAD

**Issue by wael444** [afify/sfm#49]
default behavior:
![image](https://user-images.githubusercontent.com/47404953/190180285-87d9f067-191a-47e3-98a5-98df71a5923c.png)
suggestion:
![image](https://user-images.githubusercontent.com/47404953/190180382-5d626781-0c2f-4660-ac6e-97bec8617f37.png)

**Comment by afify** [comment]
Patches are welcomed [sfm-patches](https://github.com/afify/sfm-patches)

**Comment by wael444** [comment]
i don't know C which is why i opened this issue for a feature (patch) request
