### ISSUE TITLE
please add ability to run sh files from file manager

### ISSUE THREAD

**Issue by sergey6661313** [afify/sfm#50]
why do I need a file manager that can't run files?

**Comment by sikmir** [comment]
> **b**      spawn a shell in the current directory

Why not spawn a shell and run a command?

**Comment by sergey6661313** [comment]
> > **b**      spawn a shell in the current directory
> 
> Why not spawn a shell and run a command?

I have to type in the shell the name of the file. I thought the file manager was needed for this: in order not to type anything again.

**Comment by afify** [comment]
```diff
diff --git a/config.def.h b/config.def.h
index 7aae364..d74de02 100644
--- a/config.def.h
+++ b/config.def.h
@@ -59,12 +59,14 @@ static const char *mupdf[]        = { "mupdf" };
 static const char *libreoffice[]  = { "libreoffice" };
 static const char *gimp[]         = { "gimp" };
 static const char *r2[]           = { "r2", "-c", "vv" };
+static const char *sh[]           = { "sh" };
 
 /* extensions*/
 static const char *images[]    = { "bmp", "jpg", "jpeg", "png", "gif", "webp", "xpm" };
 static const char *pdf[]       = { "epub", "pdf" };
 static const char *arts[]      = { "xcf" };
 static const char *obj[]       = { "o", "a", "so" };
+static const char *shell_ext[]     = { "sh" };
 static const char *videos[]    = { "avi", "flv", "wav", "webm", "wma", "wmv",
 				   "m2v", "m4a", "m4v", "mkv", "mov", "mp3",
 				   "mp4", "mpeg", "mpg" };
@@ -78,6 +80,7 @@ static Rule rules[] = {
 	{documents, LEN(documents), libreoffice, LEN(libreoffice) },
 	{arts,      LEN(arts),      gimp,        LEN(gimp)        },
 	{obj,       LEN(obj),       r2,          LEN(r2)          },
+	{shell_ext,     LEN(shell_ext),     sh,          LEN(sh)          },
 };
 
 /* normal keys */

```

**Comment by sergey6661313** [comment]
> ```diff
> diff --git a/config.def.h b/config.def.h
> index 7aae364..d74de02 100644
> --- a/config.def.h
> +++ b/config.def.h
> @@ -59,12 +59,14 @@ static const char *mupdf[]        = { "mupdf" };
>  static const char *libreoffice[]  = { "libreoffice" };
>  static const char *gimp[]         = { "gimp" };
>  static const char *r2[]           = { "r2", "-c", "vv" };
> +static const char *sh[]           = { "sh" };
>  
>  /* extensions*/
>  static const char *images[]    = { "bmp", "jpg", "jpeg", "png", "gif", "webp", "xpm" };
>  static const char *pdf[]       = { "epub", "pdf" };
>  static const char *arts[]      = { "xcf" };
>  static const char *obj[]       = { "o", "a", "so" };
> +static const char *shell_ext[]     = { "sh" };
>  static const char *videos[]    = { "avi", "flv", "wav", "webm", "wma", "wmv",
>  				   "m2v", "m4a", "m4v", "mkv", "mov", "mp3",
>  				   "mp4", "mpeg", "mpg" };
> @@ -78,6 +80,7 @@ static Rule rules[] = {
>  	{documents, LEN(documents), libreoffice, LEN(libreoffice) },
>  	{arts,      LEN(arts),      gimp,        LEN(gimp)        },
>  	{obj,       LEN(obj),       r2,          LEN(r2)          },
> +	{shell_ext,     LEN(shell_ext),     sh,          LEN(sh)          },
>  };
>  
>  /* normal keys */
> ```
```

[sfm-0.4]$ make
sfm build options:
CFLAGS   = -std=c99 -pedantic -Wextra -Wall -Wno-unused-parameter -Os -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DVERSION="0.4"
LDFLAGS  = -pthread -s
CC       = cc
cc -c -std=c99 -pedantic -Wextra -Wall -Wno-unused-parameter -Os -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DVERSION=\"0.4\" sfm.c
In file included from sfm.c:227:
config.h:57:20: error: conflicting types for 'sh'; have 'const char *[]'
   57 | static const char *sh[]           = { "sh"};
      |                    ^~
sfm.c:200:13: note: previous definition of 'sh' with type 'char[8]'
  200 | static char sh[] = "/bin/sh";
      |             ^~
sfm.c: In function 'get_shell':
sfm.c:1875:26: warning: assignment to 'char *' from incompatible pointer type 'const char **' [-Wincompatible-pointer-types]
 1875 |                 shell[0] = sh;
      |                          ^
sfm.c: At top level:
sfm.c:200:13: warning: 'sh' defined but not used [-Wunused-variable]
  200 | static char sh[] = "/bin/sh";
      |             ^~
make: *** [Makefile:18: sfm.o] Error 1
```
