### ISSUE TITLE
File types and default programs

### ISSUE THREAD

**Issue by ddkn** [afify/sfm#9]
Hello!

I have been playing around with `sfm` and it is very neat and lightweight! I was wondering on the choices on default applications. Would it be useful to not have apps choose between (or fall back to) `xdg-open` or some predefined apps? I am sure you have thought of this, but having a configuration file of some sort to set some defaults? Or define new filetypes that an be added to the images/arts/pdf/obj/etc... extensions. I was curious if this was in the works.

Otherwise awesome!

**Comment by afify** [comment]
Customization is made  by creating a custom config.h and (re)compiling the source code. This keeps it fast, secure and simple (suckless style)
Sure i understand your point about choosing default apps, we could change them. but i think it should be done at compile time not runtime.

**Comment by ddkn** [comment]
Hm, I see your point, I suppose it is a trade off of convenience. But it does limit sfm from being packaged. I suppose this is how dwm works, which is nice, but I think in the case of a file manager that can open apps that convenience has a place. Since users can have very different apps.

Would you be open to read aliases from the environment that override the config.h settings? Even adding xdg-open as a fallback could be handy. That doesn't seem like too much overhead, as there shouldn't be much difference between changing the config.h and setting a alias in function. Just one is more convenient than the other. I suppose if you are worried of a rogue agent changing someones alias to be dangerous, you have other problems on the said system.

I could be wrong, but it is nice being able to move .profiles or .*shrc files onto systems. Something in the vein of `nnn`

**Comment by ddkn** [comment]
Oh, actually something that may be simpler and keep things lightweight would be another option like `l:open` but another letter (maybe `ESC`?). It expects a command from the user where the active or currently highlighted file is an argument.

So if you are hovering over sfm.c and you hit `<new key>` the status bar turns into a `$` of the current users shell then you can do,

    $ emacs

and sfm.c is passed to that command.

*Mind you I use vis-editor, but emacs was an example, haha*
